"""
Django settings for resume_service project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# from celery.schedules import crontab
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


if DEBUG:
    ALLOWED_HOSTS = [
        "*",
        "127.0.0.1",
        "localhost",
        "diverse-intense-whippet.ngrok-free.app",
        "osamaaslam.pythonanywhere.com",
    ]
else:
    ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "resume",
    "requests",
    "rest_framework",
    "corsheaders",
    "formtools",
    "crispy_forms",
    "crispy_bootstrap5",
    "drf_spectacular",
]

# Maintenance Mode Middleware
MAINTENANCE_MODE = False

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "resume_service.maintainance_middleware.MaintenanceModeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "resume_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "resume_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     },
# }

DATABASES = {
    "default": {
        # Resume service DB
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "resume_db",
        "USER": "resume_service",
        "PASSWORD": "Osama1122334455!",
        "HOST": "database-2.c5e8gciyogx5.us-east-1.rds.amazonaws.com",
        "PORT": "5432",
    },
}

# Cache configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "alternate": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    },
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"


# --------------------------- CORS settings-------------------
CORS_ALLOWED_ORIGINS = [
    "https://lnomtkmn5h.execute-api.us-east-1.amazonaws.com",
    "https://osama11111.pythonanywhere.com",
    "https://osamaaslam.pythonanywhere.com",
    "https://web.postman.co",
    "https://diverse-intense-whippet.ngrok-free.app",
    "http://127.0.0.1",
    "https://resume-builder-integrated-with-resume-api.vercel.app",
    "https://resume-builder-pwa.vercel.app",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "X-RateLimit-Limit",
    "X-RateLimit-Remaining",
]


if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "https://lnomtkmn5h.execute-api.us-east-1.amazonaws.com",
        "http://127.0.0.1",
        "https://web.postman.co",
        "https://diverse-intense-whippet.ngrok-free.app",
        "https://osamaaslam.pythonanywhere.com",
        "https://osama11111.pythonanywhere.com",
        "https://resume-builder-integrated-with-resume-api.vercel.app",
    ]
else:
    # authenticate teh request only, checking if it has CSRF token comming here from django-e-commrace
    CSRF_TRUSTED_ORIGINS = [
        "https://lnomtkmn5h.execute-api.us-east-1.amazonaws.com",
        "https://osamaaslam.pythonanywhere.com",
        "https://osama11111.pythonanywhere.com",
        "https://web.postman.co",
        "https://diverse-intense-whippet.ngrok-free.app",
        "https://resume-builder-integrated-with-resume-api.vercel.app",
    ]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# crispy form
CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "resume_service.custom_user_rated_throtle_class.CustomAnonRateThrottle",
        "resume_service.custom_user_rated_throtle_class.CustomUserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "200/hour",
        "user": "200/hour",
    },
    "DATE_INPUT_FORMATS": ["%d-%m-%Y"],
    "DATE_FORMAT": "%Y-%m-%d",
    "DATETIME_FORMAT": "%Y-%m-%d %H",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Resume API",
    "DESCRIPTION": "API documentation for Resume API",
    "VERSION": "1.0.0",
    "COMPONENT_SPLIT_REQUEST": True,
    "SERVE_INCLUDE_SCHEMA": True,
    "SCHEMA_PATH_PREFIX": "/dev",  # Important for stripping `/dev` from URL patterns
    "SERVE_ROOT": "/dev",  # Makes the schema URL itself start with /dev
    "SERVERS": [
        {
            "url": "https://lnomtkmn5h.execute-api.us-east-1.amazonaws.com/dev",
        }
    ],
    # Method: 1
    "PREPROCESSING_HOOKS": [
        "resume_service.excluded_path_drf_spectacular_schema.custom_preprocessing_hook",
    ],
    # Method 2: Use @extend_schema(exclude=True) by placing it on top of the View / Action
    "AUTHENTICATION_WHITELIST": [
        "custom_restframework_simplejwt.authentication.JWTStatelessUserAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "PARSER_WHITELIST": ["rest_framework.parsers.JSONParser"],
    "RENDERER_WHITELIST": ["rest_framework.renderers.JSONRenderer"],
}


from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=2500),
    "ALGORITHM": "HS256",
    "SIGNING_KEY": config("JWT_SHARED_SECRET_KEY"),
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "AUTH_TOKEN_CLASSES": ("custom_restframework_simplejwt.tokens.AccessToken",),
    "TOKEN_USER_CLASS": "custom_restframework_simplejwt.models.TokenUser",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_TYPE_CLAIM": "token_type",  # This tells the validator to look at the "token_type" field in the payload to determine if the token is an access or refresh token.
    "JTI_CLAIM": "jti",
    "CHECK_USER_IS_ACTIVE": True,
}


# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        # "file": {
        #     "class": "logging.FileHandler",
        #     "filename": os.path.join(BASE_DIR, "logs", "django_debug.log"),
        #     "formatter": "verbose",
        # },
        # "resume_file": {  # NEW: Log file for all logs related to the 'resume' app
        #     "class": "logging.FileHandler",
        #     "filename": os.path.join(BASE_DIR, "logs", "resume.log"),
        #     "formatter": "verbose",
        # },
    },
    "loggers": {
        "django": {
            # "handlers": ["console", "file"],
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "resume": {  # NEW: Logs everything related to 'resume', including management commands
            # "handlers": ["console", "resume_file"],
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "drf_spectacular": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}
