"""
Django settings for user_service project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# Zappa Stage
STAGE = config("STAGE")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

if DEBUG:
    ALLOWED_HOSTS = [
        "*",
        "127.0.0.1",
        "localhost",
        "diverse-intense-whippet.ngrok-free.app",
        "osamaaslam.pythonanywhere.com",
    ]
else:
    ALLOWED_HOSTS = ["*", "osamaaslam.pythonanywhere.com"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "api_auth",
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
]

# Maintenance Mode Middleware
MAINTENANCE_MODE = False

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "user_service.maintainance_middleware.MaintenanceModeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "user_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "user_service.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "user_service_db",
        "USER": "user_service",
        "PASSWORD": "Osama1122334455!",
        "HOST": "database-1.c5e8gciyogx5.us-east-1.rds.amazonaws.com",
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
# STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cache configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
    "alternate": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    },
}

CORS_ALLOWED_ORIGINS = [
    "https://l8tmowpqw5.execute-api.us-east-1.amazonaws.com",
    "https://osama11111.pythonanywhere.com",
    "https://osamaaslam.pythonanywhere.com",
    "https://web.postman.co",
    "https://diverse-intense-whippet.ngrok-free.app",
    "http://127.0.0.1",
    "https://resume-builder-integrated-with-resume-api.vercel.app",
    "https://resume-builder-pwa.vercel.app",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "X-RateLimit-Limit",
    "X-RateLimit-Remaining",
]


if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "https://l8tmowpqw5.execute-api.us-east-1.amazonaws.com",
        "http://127.0.0.1",
        "https://web.postman.co",
        "https://diverse-intense-whippet.ngrok-free.app",
        "https://osamaaslam.pythonanywhere.com",
        "https://osama11111.pythonanywhere.com",
        "https://resume-builder-integrated-with-resume-api.vercel.app",
    ]
else:
    # authenticate teh request only, checking if it has CSRF token comming here from django-e-commrace
    CSRF_TRUSTED_ORIGINS = [
        "https://l8tmowpqw5.execute-api.us-east-1.amazonaws.com",
        "https://osamaaslam.pythonanywhere.com",
        "https://osama11111.pythonanywhere.com",
        "https://web.postman.co",
        "https://diverse-intense-whippet.ngrok-free.app",
        "https://resume-builder-integrated-with-resume-api.vercel.app",
    ]


# User Model
AUTH_USER_MODEL = "api_auth.CustomUser"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "api_auth.custom_user_rated_throtle_class.CustomAnonRateThrottle",
        "api_auth.custom_user_rated_throtle_class.CustomUserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "200/hour",
        "user": "200/hour",
    },
    # "DATE_INPUT_FORMATS": ["%d-%m-%Y"],
    # "DATE_FORMAT": "%Y-%m-%d",
    # "DATETIME_FORMAT": "%Y-%m-%d %H",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "User Service API",
    "DESCRIPTION": "Documentation for User API",
    "VERSION": "1.0.0",
    "COMPONENT_SPLIT_REQUEST": True,
    "SERVE_INCLUDE_SCHEMA": True,
    # "SECURITY_SCHEMES": { # see drf-spectacular.extension.py
    #     "BearerAuth": {
    #         "type": "http",
    #         "scheme": "bearer",
    #         "bearerFormat": "JWT",
    #     }
    # },
    "SCHEMA_PATH_PREFIX": "/dev",  # Important for stripping `/dev` from URL patterns
    "SERVE_ROOT": "/dev",  # Makes the schema URL itself start with /dev
    "SERVERS": [
        {
            "url": "https://l8tmowpqw5.execute-api.us-east-1.amazonaws.com/dev",
        }
    ],
    "SERVE_PERMISSIONS": [],  # ← allows unauthenticated access
    # Method: 1
    "PREPROCESSING_HOOKS": [
        "user_service.excluded_path_drf_spectacular_schema.custom_preprocessing_hook",
    ],
    # Method 2: Use @extend_schema(exclude=True) by placing it on top of the View / Action
    "AUTHENTICATION_WHITELIST": [
        "rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication",
    ],
    "PARSER_WHITELIST": ["rest_framework.parsers.JSONParser"],
    "RENDERER_WHITELIST": ["rest_framework.renderers.JSONRenderer"],
}


from datetime import timedelta

# Disable DRF built-in session authentication
REST_SESSION_LOGIN = False

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=2500),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=10),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,  # must be False for StatelessAuth
    "ALGORITHM": "HS256",
    "SIGNING_KEY": config("JWT_SHARED_SECRET_KEY"),
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "TOKEN_OBTAIN_SERIALIZER": "api_auth.serializers.TokenClaimObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "custom_simplejwt.serializers.CustomTokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


# -------------Specifically for drf_spectacular----------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        # "file": {
        #     "class": "logging.FileHandler",
        #     "filename": os.path.join(BASE_DIR, "logs", "django_debug.log"),
        #     "formatter": "verbose",
        # },
        # "resume_file": {  # NEW: Log file for all logs related to the 'resume' app
        #     "class": "logging.FileHandler",
        #     "filename": os.path.join(BASE_DIR, "logs", "resume.log"),
        #     "formatter": "verbose",
        # },
    },
    "loggers": {
        "django": {
            # "handlers": ["console", "file"],
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "api_auth": {  # You can replace this with your actual app name
            # "handlers": ["console", "file"],
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "resume": {  # NEW: Logs everything related to 'resume', including management commands
            # "handlers": ["console", "resume_file"],
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "drf_spectacular": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}
